# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{mongoa}
  s.version = "0.1.10"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Scott J. Tamosunas"]
  s.date = %q{2010-08-12}
  s.description = %q{Adds the association and validation macros for Rspec in the same way Shoulda does for ActiveRecord.}
  s.email = %q{tamosunas@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "lib/mongoa.rb",
     "lib/mongoa/integrations/rspec2.rb",
     "lib/mongoa/mongo_mapper/association_matcher.rb",
     "lib/mongoa/mongo_mapper/improvements/mongo_mapper_associations.rb",
     "lib/mongoa/mongo_mapper/matchers.rb",
     "lib/mongoa/mongo_mapper/validations.rb",
     "lib/mongoa/mongo_mapper/validations/validate_base.rb",
     "lib/mongoa/mongo_mapper/validations/validate_inclusion_of.rb",
     "lib/mongoa/mongo_mapper/validations/validate_length_of.rb",
     "lib/mongoa/mongo_mapper/validations/validate_presence_of.rb",
     "mongoa.gemspec",
     "spec/association_matcher_spec.rb",
     "spec/spec.opts",
     "spec/spec_helper.rb",
     "spec/validation_matcher_spec.rb"
  ]
  s.homepage = %q{http://github.com/scotttam/mongoa}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Like Shoulda but for MongoMapper.}
  s.test_files = [
    "spec/association_matcher_spec.rb",
     "spec/spec_helper.rb",
     "spec/validation_matcher_spec.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 1.2.9"])
    else
      s.add_dependency(%q<rspec>, [">= 1.2.9"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 1.2.9"])
  end
end

